import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { content, company } from '../src/content.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
await mkdir(path.join(out,'assets'), {recursive:true});
for (const f of ['style.css','site.js','favicon.svg']) await copyFile(path.join(root,'src',f),path.join(out,'assets',f));
const esc = s => String(s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines = s => esc(s).replace(/\n/g,'<br>');
const arrow = '<span aria-hidden="true">↗</span>';
const pages = ['home','about','focus','contact','privacy','terms'];
const icons = [
  '<path d="M5 12h22M20 5l7 7-7 7M27 26H5m7-7-7 7 7 7"/>',
  '<rect x="5" y="7" width="24" height="22" rx="3"/><path d="M5 14h24M11 23h7"/>',
  '<path d="m11 8-8 10 8 10m12-20 8 10-8 10M20 5l-6 26"/>'
];
const icon = i => `<svg viewBox="0 0 36 36" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[i]}</svg>`;
for (const lang of ['en','zh']) {
 const t=content[lang], other=lang==='en'?'zh':'en';
 for(const page of pages){
  const nested=page!=='home', prefix=nested?'../../':'../', link=p=>p==='home'?(nested?'../':'./'):(nested?`../${p}/`:`${p}/`);
  const asset=`${prefix}assets/`, alt=`${prefix}${other}/${nested?page+'/':''}`;
  const badge=`<span class="badge">${t.planned}</span>`;
  const notice=`<aside class="notice"><span class="notice-mark" aria-hidden="true">i</span><div><strong>${t.noteTitle}</strong><p>${t.notice}</p></div></aside>`;
  const cta=`<section class="contact-band"><div><p class="eyebrow">${t.ctaLabel}</p><h2>${lines(t.ctaTitle)}</h2></div><div><p>${t.ctaText}</p><a class="email-link" href="mailto:${company.email}">${company.email} ${arrow}</a></div></section>`;
  const principles=`<section class="section principles"><div class="section-head"><p class="eyebrow">${t.principlesLabel}</p><h2>${t.principlesTitle}</h2><p>${t.principlesIntro}</p></div><div class="principle-grid">${t.principles.map(([title,text],i)=>`<article><span class="index">0${i+1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>`;
  const tiles=`<div class="cards">${t.areas.map((a,i)=>`<article class="card"><div class="card-top">${icon(i)}${badge}</div><p class="small-label">${a.short}</p><h3>${a.title}</h3><p>${a.text}</p><a class="text-link" href="${link('focus')}#${a.id}">${t.detail} ${arrow}</a></article>`).join('')}</div>`;
  const pagehead=(label,desc='')=>`<section class="page-head"><p class="eyebrow">${label}</p><h1>${t.pages[page]}</h1>${desc?`<p class="lead">${desc}</p>`:''}</section>`;
  let body='';
  if(page==='home')body=`<section class="hero"><div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><h1>${t.hero.map((s,i)=>`<span${i===2?' class="accent"':''}>${s}</span>`).join('')}</h1><p class="lead">${t.intro}</p><div class="actions"><a class="button" href="${link('focus')}">${t.explore}${arrow}</a><a class="text-link" href="${link('contact')}">${t.contact}${arrow}</a></div></div><div class="hero-visual" aria-hidden="true"><div class="orbital orbital-one"></div><div class="orbital orbital-two"></div><div class="orbital orbital-three"></div><div class="visual-axis axis-one"></div><div class="visual-axis axis-two"></div><span class="visual-top">BG / PERSPECTIVES</span><span class="visual-bottom">CONNECTING IDEAS.<br>SHAPING POSSIBILITIES.</span><div class="visual-monogram">BG<span>TECHNOLOGY</span></div><span class="visual-number">01 — 03</span></div></section><div class="stage-strip"><span>${t.status}</span><p>${t.shortStatus}</p></div><section class="section company-section"><p class="eyebrow">${t.companyLabel}</p><div><h2>${lines(t.companyTitle)}</h2><p>${t.companyText}</p><a class="text-link" href="${link('about')}">${t.aboutLink}${arrow}</a></div></section><section class="section focus-section"><div class="section-heading"><div><p class="eyebrow">${t.focusLabel}</p><h2>${lines(t.focusTitle)}</h2></div><p>${t.focusIntro}</p></div>${tiles}</section>${principles}${notice}${cta}`;
  if(page==='about')body=`${pagehead(t.companyLabel,t.companyText)}<section class="about-panel"><div class="about-type" aria-hidden="true">BG<span>TECHNOLOGY</span></div><div><p class="eyebrow">${t.legalEntity}</p><h2>${company.name}</h2><p>${t.intro}</p>${company.uen?`<p>${t.registration}: ${esc(company.uen)}</p>`:''}${company.address?`<p>${esc(company.address)}</p>`:''}</div></section>${principles}${notice}${cta}`;
  if(page==='focus')body=`${pagehead(t.focusLabel,t.focusIntro)}${notice}<div class="area-list">${t.areas.map((a,i)=>`<section id="${a.id}" class="area-detail"><div class="area-number">0${i+1}</div><div><div class="area-title">${icon(i)}${badge}</div><h2>${a.title}</h2><p class="lead">${a.text}</p></div><div class="area-support"><h3>${t.contexts}</h3><ul>${a.contexts.map(x=>`<li>${x}</li>`).join('')}</ul><h3>${t.thinking}</h3><p>${a.thinking}</p></div></section>`).join('')}</div>${cta}`;
  if(page==='contact')body=`${pagehead(t.contactLabel,t.ctaText)}<section class="contact-layout"><div class="contact-primary"><span class="eyebrow">${t.emailLabel}</span><a class="contact-email" href="mailto:${company.email}">${company.email}${arrow}</a><p>${t.contactNote}</p></div><div class="contact-company"><p class="eyebrow">${t.legalEntity}</p><h2>${company.name}</h2>${company.uen?`<p>${t.registration}: ${esc(company.uen)}</p>`:''}${company.address?`<p>${t.address}: ${esc(company.address)}</p>`:''}<span class="badge">${t.status}</span></div></section>${notice}`;
  if(page==='privacy'||page==='terms')body=`${pagehead(page==='privacy'?t.privacy:t.terms,t.legalIntro)}<article class="legal">${t[page+'Sections'].map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}</article>`;
  const html=`<!doctype html><html lang="${t.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(t.description)}"><meta name="theme-color" content="#142e39"><title>${esc(t.pages[page])} | BG Technology</title><link rel="icon" type="image/svg+xml" href="${asset}favicon.svg"><link rel="stylesheet" href="${asset}style.css"><link rel="alternate" hreflang="${content[other].lang}" href="${alt}"><script defer src="${asset}site.js"></script></head><body data-language="${lang}"><a class="skip" href="#main">${t.skip}</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="${link('home')}" aria-label="BG Technology — ${t.nav[0]}"><span class="brand-mark">BG</span><span class="brand-text">BG TECHNOLOGY<small>VENTURE PTE LTD</small></span></a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" data-open="${t.menu}" data-close="${t.close}">${t.menu}<span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="${lang==='en'?'Main navigation':'主导航'}">${['home','about','focus','contact'].map((p,i)=>`<a href="${link(p)}"${p===page?' aria-current="page"':''}>${t.nav[i]}</a>`).join('')}<a class="language" data-language="${other}" href="${alt}" lang="${content[other].lang}" aria-label="${other==='zh'?'切换为中文':'Switch to English'}">${t.other}</a></nav></div></header><main id="main" class="container">${body}</main><footer><div class="container footer-main"><div><a class="brand footer-brand" href="${link('home')}"><span class="brand-mark">BG</span><span class="brand-text">BG TECHNOLOGY<small>VENTURE PTE LTD</small></span></a><p>${t.footerText}</p></div><div><span class="eyebrow">${t.contactLabel}</span><a href="mailto:${company.email}">${company.email}</a><p>${company.name}${company.uen?`<br>${t.registration}: ${esc(company.uen)}`:''}${company.address?`<br>${esc(company.address)}`:''}</p></div></div><div class="container footer-bottom"><p>© ${new Date().getFullYear()} ${company.name}. ${t.rights}</p><div><a href="${link('privacy')}">${t.privacy}</a><a href="${link('terms')}">${t.terms}</a></div><p class="footer-status">${t.footerStatus}</p></div></footer></body></html>`;
  const dir=path.join(out,lang,nested?page:'');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),html);
 }
}
await writeFile(path.join(out,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BG Technology</title><meta name="description" content="BG Technology Venture Pte Ltd corporate website"><link rel="icon" href="assets/favicon.svg"><script src="assets/site.js" defer></script></head><body data-entry="true"><p><a href="en/">Continue in English</a> · <a href="zh/">中文版</a></p></body></html>`);
await writeFile(path.join(out,'404.html'),'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | BG Technology</title></head><body><h1>Page not found / 页面不存在</h1><p>Please check the address or use your browser to return to the previous page.</p><p>请检查网址，或使用浏览器返回上一页。</p></body></html>');
await writeFile(path.join(out,'.nojekyll'),'');
console.log('Built 12 bilingual pages, language entry and 404 in dist/.');
